export default {
    sketchAudio1: false,
    sketchAudio2: false,
    sketchAudio3: false,
    sketchAudio4: false,
    sketchAudio5: false,
    startButton: true,
    recordButton: false,
    playButton: false,
    pauseButton: false,
    clearButton: false,
    canvasCircleWidth: 300,
    canvasCircleHeight: 300,
    canvasHorizWidth: 100,
    canvasHorizHeight: 300,
    canvasVertWidth: 300,
    canvasVertHeight: 100,
    recordGesture: false,
    playGesture: false,
    recordedData: false,
    playError: false,
    slider: 0,
    showSlider: false,
    showGesture: false,
    checkbox: false,
    speedScaler: 1,
    speeds: [1, 1, 1, 1, 1, 1, 0.5, 2, 0.5, 0.25, 2, 0.25, 0.1, 0.1, 1],
    sectionNum: 0,
    readyToGo: false,
    sliderMax: 100,
    showTitle: true,
};
